name: Request Access to Private Repository
description: Submit this form to request access to a private repository.
title: "[Access Request] Request access for {username}"
labels: access-request
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for your interest in accessing our Course!**  
        Please fill out the required fields below to submit your request.

  - type: input
    id: github_username
    attributes:
      label: GitHub Username
      description: Provide your GitHub username (e.g., john-doe). Ensure it's accurate so we can process your request.
      placeholder: Enter your GitHub username
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: Please agree to the terms below to proceed.
      options:
        - label: I understand that this access is for read-only purposes, and I agree to use the repository responsibly.
          required: true
